# Префикс для LAN сети
BRIDGE_NET="192.168.99."
# INTERNAL_NET="192.168.15."
# DOMAIN="wibob.local"
servers=[
  {
    :hostname => "git",
    :ip => BRIDGE_NET + "151",
   # :ip_int => "1",
    :ram => 1000
  },
  {
    :hostname => "ansible",
    :ip => BRIDGE_NET + "152",
    # :ip_int => "2",
    :ram => 1000,
    # :hdd_name => "db1_hdd.vdi",
    # :hdd_size => "10000"
  },
]

Vagrant.configure(2) do |config|
    # Добавить шару между хостовой и гостевой машиной
    #config.vm.synced_folder "D://hostmachine/shared/folder", "/src/shara"
    # Отключить дефолтную шару
    # config.vm.synced_folder ".", "/vagrant", disabled: true
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = "hashicorp/bionic64"
            # Также, можно указать URL откуда стянуть нужный box если такой есть
            # node.vm.box_url = "http://files.vagrantup.com/precise64.box"
            node.vm.usable_port_range = (2200..2250)
            node.vm.hostname = machine[:hostname]
            #VBoxManage.exe list bridgedifs overwrite NAT adapter :adapter=>1
            # Добавление и настройка Bridge сетевого адаптера(моста). Чтобы узнать точное название birdge адаптера, нужно использовать VBoxManage.exe (смотрите ниже)
            node.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'
            # Добавление и настройка внутреннего сетевого адаптера (Intnet)
            node.vm.network "private_network", ip: machine[:ip], virtualbox__intnet: "intnet"
            #node.ssh.host = machine[:ip]
            #node.ssh.private_key_path = "private_key"
            node.ssh.username = "vagrant"
            node.ssh.password = "vagrant"
            # Тонкие настройки для конкретного провайдера (в нашем случаи - VBoxManage)
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.name = machine[:hostname]
                # Добавление жесткого диска, если такой указан в конфигурации
                # if (!machine[:hdd_name].nil?)
                #     # Не создавать диск, если он уже существует
                #     unless File.exist?(machine[:hdd_name])
                #         vb.customize ["createhd", "--filename", machine[:hdd_name], "--size", machine[:hdd_size]]
                #     end
                #     # Подключить созданный диск к поточной VM
                #     vb.customize ["storageattach", :id, "--storagectl", "SATA", "--port", 1, "--device", 0, "--type", "hdd", "--medium", machine[:hdd_name]]
                # end
                # Где хранить snapshot
                #vb.customize ["modifyvm", :id, "--snapshotfolder", "D:\\test"]
                # Еще один способ сменить название VM в Vbox GUI
                #vb.customize ["modifyvm", :id, "--name", "Gangnam Style"]
            end
        end
    end
end
